version: "3"
services:
  webpack-dev-server:
    build: .
    environment:
      - WEBPACK_HOST=0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
      - /app/node_modules # register node_modules directory to volumes
